//! Standard permission catalog seeds written to `iam_permission`.
//! Canonical source: `iam/modules/*/iam.module.manifest.json` materialized by `sdkwork-iam-module-registry`.
//! This module retains iam-kernel permissions for backward-compatible tests only.
use crate::PermissionSeed;

pub const IAM_STANDARD_PERMISSION_SEEDS: &[PermissionSeed] = &[
    PermissionSeed {
        code: "*",
        name: "Global wildcard permission",
        resource: "*",
        action: "*",
    },
    PermissionSeed {
        code: "iam:self",
        name: "Self-service IAM scope",
        resource: "iam",
        action: "self",
    },
    PermissionSeed {
        code: "iam.access_credentials.create",
        name: "Create delegated access credentials",
        resource: "iam.access_credentials",
        action: "create",
    },
    PermissionSeed {
        code: "iam.account_binding_policy.read",
        name: "Read account binding policy",
        resource: "iam.account_binding_policy",
        action: "read",
    },
    PermissionSeed {
        code: "iam.account_binding_policy.update",
        name: "Update account binding policy",
        resource: "iam.account_binding_policy",
        action: "update",
    },
    PermissionSeed {
        code: "iam.api_keys.read",
        name: "Read API keys",
        resource: "iam.api_keys",
        action: "read",
    },
    PermissionSeed {
        code: "iam.api_keys.revoke",
        name: "Revoke API keys",
        resource: "iam.api_keys",
        action: "revoke",
    },
    PermissionSeed {
        code: "iam.applications.register",
        name: "Register applications",
        resource: "iam.applications",
        action: "register",
    },
    PermissionSeed {
        code: "iam.assignments.create",
        name: "Create department and position assignments",
        resource: "iam.assignments",
        action: "create",
    },
    PermissionSeed {
        code: "iam.assignments.deactivate",
        name: "Deactivate department and position assignments",
        resource: "iam.assignments",
        action: "deactivate",
    },
    PermissionSeed {
        code: "iam.assignments.read",
        name: "Read department and position assignments",
        resource: "iam.assignments",
        action: "read",
    },
    PermissionSeed {
        code: "iam.assignments.update",
        name: "Update department and position assignments",
        resource: "iam.assignments",
        action: "update",
    },
    PermissionSeed {
        code: "iam.audit_events.read",
        name: "Read IAM audit events",
        resource: "iam.audit_events",
        action: "read",
    },
    PermissionSeed {
        code: "iam.departments.create",
        name: "Create departments",
        resource: "iam.departments",
        action: "create",
    },
    PermissionSeed {
        code: "iam.departments.delete",
        name: "Delete departments",
        resource: "iam.departments",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.departments.manage",
        name: "Manage departments",
        resource: "iam.departments",
        action: "manage",
    },
    PermissionSeed {
        code: "iam.departments.read",
        name: "Read departments",
        resource: "iam.departments",
        action: "read",
    },
    PermissionSeed {
        code: "iam.departments.update",
        name: "Update departments",
        resource: "iam.departments",
        action: "update",
    },
    PermissionSeed {
        code: "iam.group_members.create",
        name: "Add IAM group members",
        resource: "iam.group_members",
        action: "create",
    },
    PermissionSeed {
        code: "iam.group_members.delete",
        name: "Remove IAM group members",
        resource: "iam.group_members",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.group_members.read",
        name: "Read IAM group members",
        resource: "iam.group_members",
        action: "read",
    },
    PermissionSeed {
        code: "iam.groups.create",
        name: "Create IAM groups",
        resource: "iam.groups",
        action: "create",
    },
    PermissionSeed {
        code: "iam.groups.delete",
        name: "Delete IAM groups",
        resource: "iam.groups",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.groups.read",
        name: "Read IAM groups",
        resource: "iam.groups",
        action: "read",
    },
    PermissionSeed {
        code: "iam.groups.update",
        name: "Update IAM groups",
        resource: "iam.groups",
        action: "update",
    },
    PermissionSeed {
        code: "iam.memberships.create",
        name: "Create organization memberships",
        resource: "iam.memberships",
        action: "create",
    },
    PermissionSeed {
        code: "iam.memberships.deactivate",
        name: "Deactivate organization memberships",
        resource: "iam.memberships",
        action: "deactivate",
    },
    PermissionSeed {
        code: "iam.memberships.read",
        name: "Read organization memberships",
        resource: "iam.memberships",
        action: "read",
    },
    PermissionSeed {
        code: "iam.memberships.update",
        name: "Update organization memberships",
        resource: "iam.memberships",
        action: "update",
    },
    PermissionSeed {
        code: "iam.oauth.manage",
        name: "Manage OAuth administration resources",
        resource: "iam.oauth",
        action: "manage",
    },
    PermissionSeed {
        code: "iam.oauth.read",
        name: "Read OAuth administration resources",
        resource: "iam.oauth",
        action: "read",
    },
    PermissionSeed {
        code: "iam.organizations.create",
        name: "Create organizations",
        resource: "iam.organizations",
        action: "create",
    },
    PermissionSeed {
        code: "iam.organizations.delete",
        name: "Delete organizations",
        resource: "iam.organizations",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.organizations.read",
        name: "Read organizations",
        resource: "iam.organizations",
        action: "read",
    },
    PermissionSeed {
        code: "iam.organizations.update",
        name: "Update organizations",
        resource: "iam.organizations",
        action: "update",
    },
    PermissionSeed {
        code: "iam.permissions.create",
        name: "Create IAM permissions",
        resource: "iam.permissions",
        action: "create",
    },
    PermissionSeed {
        code: "iam.permissions.delete",
        name: "Delete IAM permissions",
        resource: "iam.permissions",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.permissions.manage",
        name: "Manage IAM permissions",
        resource: "iam.permissions",
        action: "manage",
    },
    PermissionSeed {
        code: "iam.permissions.read",
        name: "Read IAM permissions",
        resource: "iam.permissions",
        action: "read",
    },
    PermissionSeed {
        code: "iam.permissions.update",
        name: "Update IAM permissions",
        resource: "iam.permissions",
        action: "update",
    },
    PermissionSeed {
        code: "iam.policies.create",
        name: "Create IAM policies",
        resource: "iam.policies",
        action: "create",
    },
    PermissionSeed {
        code: "iam.policies.delete",
        name: "Delete IAM policies",
        resource: "iam.policies",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.policies.read",
        name: "Read IAM policies",
        resource: "iam.policies",
        action: "read",
    },
    PermissionSeed {
        code: "iam.policies.update",
        name: "Update IAM policies",
        resource: "iam.policies",
        action: "update",
    },
    PermissionSeed {
        code: "iam.positions.create",
        name: "Create positions",
        resource: "iam.positions",
        action: "create",
    },
    PermissionSeed {
        code: "iam.positions.delete",
        name: "Delete positions",
        resource: "iam.positions",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.positions.read",
        name: "Read positions",
        resource: "iam.positions",
        action: "read",
    },
    PermissionSeed {
        code: "iam.positions.update",
        name: "Update positions",
        resource: "iam.positions",
        action: "update",
    },
    PermissionSeed {
        code: "iam.profile.read",
        name: "Read own profile",
        resource: "iam.profile",
        action: "read",
    },
    PermissionSeed {
        code: "iam.profile.update",
        name: "Update own profile",
        resource: "iam.profile",
        action: "update",
    },
    PermissionSeed {
        code: "iam.provider_accounts.create",
        name: "Create provider accounts",
        resource: "iam.provider_accounts",
        action: "create",
    },
    PermissionSeed {
        code: "iam.provider_accounts.delete",
        name: "Delete provider accounts",
        resource: "iam.provider_accounts",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.provider_accounts.manage_shared",
        name: "Manage shared (tenant/organization scoped) provider accounts",
        resource: "iam.provider_accounts",
        action: "manage_shared",
    },
    PermissionSeed {
        code: "iam.provider_accounts.read",
        name: "Read provider accounts",
        resource: "iam.provider_accounts",
        action: "read",
    },
    PermissionSeed {
        code: "iam.provider_accounts.resolve",
        name: "Resolve provider accounts for consumers",
        resource: "iam.provider_accounts",
        action: "resolve",
    },
    PermissionSeed {
        code: "iam.provider_accounts.update",
        name: "Update provider accounts",
        resource: "iam.provider_accounts",
        action: "update",
    },
    PermissionSeed {
        code: "iam.provider_credentials.create",
        name: "Create provider credentials",
        resource: "iam.provider_credentials",
        action: "create",
    },
    PermissionSeed {
        code: "iam.provider_credentials.delete",
        name: "Delete provider credentials",
        resource: "iam.provider_credentials",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.provider_credentials.read",
        name: "Read provider credentials",
        resource: "iam.provider_credentials",
        action: "read",
    },
    PermissionSeed {
        code: "iam.provider_credentials.revoke",
        name: "Revoke provider credentials",
        resource: "iam.provider_credentials",
        action: "revoke",
    },
    PermissionSeed {
        code: "iam.role_bindings.create",
        name: "Create role bindings",
        resource: "iam.role_bindings",
        action: "create",
    },
    PermissionSeed {
        code: "iam.role_bindings.delete",
        name: "Delete role bindings",
        resource: "iam.role_bindings",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.role_bindings.manage",
        name: "Manage role bindings",
        resource: "iam.role_bindings",
        action: "manage",
    },
    PermissionSeed {
        code: "iam.role_bindings.read",
        name: "Read role bindings",
        resource: "iam.role_bindings",
        action: "read",
    },
    PermissionSeed {
        code: "iam.role_permissions.create",
        name: "Grant role permissions",
        resource: "iam.role_permissions",
        action: "create",
    },
    PermissionSeed {
        code: "iam.role_permissions.delete",
        name: "Revoke role permissions",
        resource: "iam.role_permissions",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.role_permissions.manage",
        name: "Manage role permissions",
        resource: "iam.role_permissions",
        action: "manage",
    },
    PermissionSeed {
        code: "iam.role_permissions.read",
        name: "Read role permissions",
        resource: "iam.role_permissions",
        action: "read",
    },
    PermissionSeed {
        code: "iam.roles.create",
        name: "Create IAM roles",
        resource: "iam.roles",
        action: "create",
    },
    PermissionSeed {
        code: "iam.roles.delete",
        name: "Delete IAM roles",
        resource: "iam.roles",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.roles.manage",
        name: "Manage IAM roles",
        resource: "iam.roles",
        action: "manage",
    },
    PermissionSeed {
        code: "iam.roles.read",
        name: "Read IAM roles",
        resource: "iam.roles",
        action: "read",
    },
    PermissionSeed {
        code: "iam.roles.update",
        name: "Update IAM roles",
        resource: "iam.roles",
        action: "update",
    },
    PermissionSeed {
        code: "iam.security_events.read",
        name: "Read IAM security events",
        resource: "iam.security_events",
        action: "read",
    },
    PermissionSeed {
        code: "iam.service_account_credentials.create",
        name: "Create IAM service account credentials",
        resource: "iam.service_account_credentials",
        action: "create",
    },
    PermissionSeed {
        code: "iam.service_account_credentials.revoke",
        name: "Revoke IAM service account credentials",
        resource: "iam.service_account_credentials",
        action: "revoke",
    },
    PermissionSeed {
        code: "iam.service_accounts.create",
        name: "Create IAM service accounts",
        resource: "iam.service_accounts",
        action: "create",
    },
    PermissionSeed {
        code: "iam.service_accounts.delete",
        name: "Delete IAM service accounts",
        resource: "iam.service_accounts",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.service_accounts.read",
        name: "Read IAM service accounts",
        resource: "iam.service_accounts",
        action: "read",
    },
    PermissionSeed {
        code: "iam.service_accounts.update",
        name: "Update IAM service accounts",
        resource: "iam.service_accounts",
        action: "update",
    },
    PermissionSeed {
        code: "iam.sessions.read",
        name: "Read own sessions",
        resource: "iam.sessions",
        action: "read",
    },
    PermissionSeed {
        code: "iam.sessions.revoke",
        name: "Revoke own sessions",
        resource: "iam.sessions",
        action: "revoke",
    },
    PermissionSeed {
        code: "iam.tenant_applications.enable",
        name: "Enable tenant applications",
        resource: "iam.tenant_applications",
        action: "enable",
    },
    PermissionSeed {
        code: "iam.tenant_applications.provision",
        name: "Provision tenant applications",
        resource: "iam.tenant_applications",
        action: "provision",
    },
    PermissionSeed {
        code: "iam.tenant_applications.update",
        name: "Update tenant applications",
        resource: "iam.tenant_applications",
        action: "update",
    },
    PermissionSeed {
        code: "iam.tenant_members.create",
        name: "Create tenant members",
        resource: "iam.tenant_members",
        action: "create",
    },
    PermissionSeed {
        code: "iam.tenant_members.delete",
        name: "Delete tenant members",
        resource: "iam.tenant_members",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.tenant_members.read",
        name: "Read tenant members",
        resource: "iam.tenant_members",
        action: "read",
    },
    PermissionSeed {
        code: "iam.tenant_members.update",
        name: "Update tenant members",
        resource: "iam.tenant_members",
        action: "update",
    },
    PermissionSeed {
        code: "iam.tenants.create",
        name: "Create IAM tenants",
        resource: "iam.tenants",
        action: "create",
    },
    PermissionSeed {
        code: "iam.tenants.delete",
        name: "Delete IAM tenants",
        resource: "iam.tenants",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.tenants.read",
        name: "Read IAM tenants",
        resource: "iam.tenants",
        action: "read",
    },
    PermissionSeed {
        code: "iam.tenants.update",
        name: "Update IAM tenants",
        resource: "iam.tenants",
        action: "update",
    },
    PermissionSeed {
        code: "iam.users.create",
        name: "Create IAM users",
        resource: "iam.users",
        action: "create",
    },
    PermissionSeed {
        code: "iam.users.delete",
        name: "Delete IAM users",
        resource: "iam.users",
        action: "delete",
    },
    PermissionSeed {
        code: "iam.users.read",
        name: "Read IAM users",
        resource: "iam.users",
        action: "read",
    },
    PermissionSeed {
        code: "iam.users.update",
        name: "Update IAM users",
        resource: "iam.users",
        action: "update",
    },
];
