[package]
name = "sdkwork-api-iam-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-iam application HTTP plane."

[lib]
name = "sdkwork_api_iam_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
serde_json.workspace = true
sdkwork_web_bootstrap = { workspace = true, features = ["sqlx"] }
sdkwork-web-contract.workspace = true
sdkwork_database_sqlx.workspace = true
sdkwork_iam_database_host = { workspace = true }
sdkwork_iam_web_adapter = { workspace = true }
sdkwork_iam_embedded_application_bootstrap.workspace = true
tracing = "0.1"
tracing-subscriber = "0.3"
sdkwork_routes_iam_app_api = { workspace = true }
sdkwork_routes_iam_backend_api = { workspace = true }
sdkwork_routes_iam_open_api = { workspace = true }

[dev-dependencies]
http-body-util = "0.1"
tokio.workspace = true
tower.workspace = true
