use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::operation_permissions::iam_backend_permission_for_operation;

const IAM_BACKEND_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenants",
        "iam",
        "tenants.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/tenants",
        "iam",
        "tenants.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/tenants/{tenantId}",
        "iam",
        "tenants.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/tenants/{tenantId}",
        "iam",
        "tenants.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/tenants/{tenantId}",
        "iam",
        "tenants.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenants/{tenantId}/members",
        "iam",
        "tenants.members.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/tenants/{tenantId}/members",
        "iam",
        "tenants.members.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/tenants/{tenantId}/members/{userId}",
        "iam",
        "tenants.members.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/tenants/{tenantId}/members/{userId}",
        "iam",
        "tenants.members.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/tenants/{tenantId}/applications",
        "iam",
        "tenantApplications.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenants/{tenantId}/applications",
        "iam",
        "tenantApplications.management.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/tenants/{tenantId}/applications/summary",
        "iam",
        "tenantApplications.summary.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/tenants/{tenantId}/applications/{tenantApplicationId}",
        "iam",
        "tenantApplications.management.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenants/{tenantId}/applications/{tenantApplicationId}/enable",
        "iam",
        "tenantApplications.management.enable",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenants/{tenantId}/applications/{tenantApplicationId}/disable",
        "iam",
        "tenantApplications.management.disable",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/organizations",
        "iam",
        "organizations.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/organizations",
        "iam",
        "organizations.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/organizations/tree",
        "iam",
        "organizations.tree.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/organizations/{organizationId}",
        "iam",
        "organizations.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/organizations/{organizationId}",
        "iam",
        "organizations.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/organizations/{organizationId}",
        "iam",
        "organizations.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/organization_memberships",
        "iam",
        "organizationMemberships.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/organization_memberships",
        "iam",
        "organizationMemberships.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/organization_memberships/{membershipId}",
        "iam",
        "organizationMemberships.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/departments",
        "iam",
        "departments.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/departments",
        "iam",
        "departments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/departments/tree",
        "iam",
        "departments.tree.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/departments/{departmentId}",
        "iam",
        "departments.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/departments/{departmentId}",
        "iam",
        "departments.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/departments/{departmentId}",
        "iam",
        "departments.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/department_assignments",
        "iam",
        "departmentAssignments.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/department_assignments",
        "iam",
        "departmentAssignments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/department_assignments/{assignmentId}",
        "iam",
        "departmentAssignments.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/positions",
        "iam",
        "positions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/positions",
        "iam",
        "positions.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/positions/{positionId}",
        "iam",
        "positions.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/positions/{positionId}",
        "iam",
        "positions.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/position_assignments",
        "iam",
        "positionAssignments.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/position_assignments",
        "iam",
        "positionAssignments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/position_assignments/{assignmentId}",
        "iam",
        "positionAssignments.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/groups",
        "iam",
        "groups.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/groups",
        "iam",
        "groups.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/groups/{groupId}",
        "iam",
        "groups.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/groups/{groupId}",
        "iam",
        "groups.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/groups/{groupId}",
        "iam",
        "groups.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/groups/{groupId}/members",
        "iam",
        "groups.members.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/groups/{groupId}/members",
        "iam",
        "groups.members.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/groups/{groupId}/members/{memberId}",
        "iam",
        "groups.members.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/service_accounts",
        "iam",
        "serviceAccounts.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/service_accounts",
        "iam",
        "serviceAccounts.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/service_accounts/{serviceAccountId}",
        "iam",
        "serviceAccounts.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/service_accounts/{serviceAccountId}",
        "iam",
        "serviceAccounts.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/service_accounts/{serviceAccountId}",
        "iam",
        "serviceAccounts.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/service_accounts/{serviceAccountId}/credentials",
        "iam",
        "serviceAccounts.credentials.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/service_account_credentials/{credentialId}/revoke",
        "iam",
        "serviceAccountCredentials.revoke",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/provider_accounts",
        "iam",
        "providerAccounts.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/provider_accounts",
        "iam",
        "providerAccounts.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/provider_accounts/resolve",
        "iam",
        "providerAccounts.resolve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/provider_accounts/{providerAccountId}",
        "iam",
        "providerAccounts.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/provider_accounts/{providerAccountId}",
        "iam",
        "providerAccounts.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/provider_accounts/{providerAccountId}",
        "iam",
        "providerAccounts.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/provider_accounts/{providerAccountId}/default",
        "iam",
        "providerAccounts.setDefault",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/provider_accounts/{providerAccountId}/credentials",
        "iam",
        "providerAccounts.credentials.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/provider_accounts/{providerAccountId}/credentials",
        "iam",
        "providerAccounts.credentials.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/provider_credentials/{credentialId}/revoke",
        "iam",
        "providerCredentials.revoke",
    ),
    HttpRoute::bootstrap_body(
        HttpMethod::Post,
        "/backend/v3/api/iam/service_account_tokens",
        "iam",
        "serviceAccountTokens.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/role_bindings",
        "iam",
        "roleBindings.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/role_bindings",
        "iam",
        "roleBindings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/role_bindings/{roleBindingId}",
        "iam",
        "roleBindings.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/users",
        "iam",
        "users.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/users",
        "iam",
        "users.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/users/{userId}",
        "iam",
        "users.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/users/{userId}",
        "iam",
        "users.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/users/{userId}",
        "iam",
        "users.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/users/{userId}/ban",
        "iam",
        "users.ban",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/users/{userId}/unban",
        "iam",
        "users.unban",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/roles",
        "iam",
        "roles.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/roles",
        "iam",
        "roles.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/roles/{roleId}",
        "iam",
        "roles.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/roles/{roleId}",
        "iam",
        "roles.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/roles/{roleId}",
        "iam",
        "roles.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/roles/{roleId}/permissions",
        "iam",
        "roles.permissions.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/roles/{roleId}/permissions",
        "iam",
        "roles.permissions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/roles/{roleId}/permissions/{permissionId}",
        "iam",
        "roles.permissions.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/permissions",
        "iam",
        "permissions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/permissions",
        "iam",
        "permissions.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/permissions/{permissionId}",
        "iam",
        "permissions.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/permissions/{permissionId}",
        "iam",
        "permissions.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/permissions/{permissionId}",
        "iam",
        "permissions.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/policies",
        "iam",
        "policies.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/policies",
        "iam",
        "policies.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/account_binding_policy",
        "iam",
        "accountBindingPolicy.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/account_binding_policy",
        "iam",
        "accountBindingPolicy.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/policies/{policyId}",
        "iam",
        "policies.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/policies/{policyId}",
        "iam",
        "policies.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/policies/{policyId}",
        "iam",
        "policies.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/api_keys",
        "iam",
        "apiKeys.list",
    ),
    HttpRoute::bootstrap_body(
        HttpMethod::Post,
        "/backend/v3/api/iam/applications/register",
        "iam",
        "applications.register",
    ),
    HttpRoute::bootstrap_body(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenant_applications",
        "iam",
        "tenantApplications.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/tenant_applications/{tenantApplicationId}",
        "iam",
        "tenantApplications.retrieve",
    ),
    HttpRoute::bootstrap_body(
        HttpMethod::Patch,
        "/backend/v3/api/iam/tenant_applications/{tenantApplicationId}",
        "iam",
        "tenantApplications.update",
    ),
    HttpRoute::bootstrap_body(
        HttpMethod::Post,
        "/backend/v3/api/iam/tenant_applications/{tenantApplicationId}/enable",
        "iam",
        "tenantApplications.enable",
    ),
    HttpRoute::bootstrap_body(
        HttpMethod::Post,
        "/backend/v3/api/iam/access_credentials",
        "iam",
        "accessCredentials.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/api_keys/{apiKeyId}/revoke",
        "iam",
        "apiKeys.revoke",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/security_events",
        "iam",
        "securityEvents.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/security_events/{securityEventId}",
        "iam",
        "securityEvents.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/audit_events",
        "iam",
        "auditEvents.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/audit_events/{auditEventId}",
        "iam",
        "auditEvents.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/provider_catalog",
        "iam.oauth",
        "iam.oauth.providerCatalog.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/provider_catalog",
        "iam.oauth",
        "iam.oauth.providerCatalog.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/provider_catalog/{providerCatalogId}",
        "iam.oauth",
        "iam.oauth.providerCatalog.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/provider_catalog/{providerCatalogId}",
        "iam.oauth",
        "iam.oauth.providerCatalog.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/integrations",
        "iam.oauth",
        "iam.oauth.integrations.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/integrations",
        "iam.oauth",
        "iam.oauth.integrations.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/integrations/{integrationId}",
        "iam.oauth",
        "iam.oauth.integrations.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/integrations/{integrationId}",
        "iam.oauth",
        "iam.oauth.integrations.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/integrations/{integrationId}",
        "iam.oauth",
        "iam.oauth.integrations.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/clients",
        "iam.oauth",
        "iam.oauth.clients.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/clients",
        "iam.oauth",
        "iam.oauth.clients.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/clients/{oauthClientId}",
        "iam.oauth",
        "iam.oauth.clients.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/clients/{oauthClientId}",
        "iam.oauth",
        "iam.oauth.clients.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/clients/{oauthClientId}",
        "iam.oauth",
        "iam.oauth.clients.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/secrets",
        "iam.oauth",
        "iam.oauth.secrets.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/secrets",
        "iam.oauth",
        "iam.oauth.secrets.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/secrets/{secretId}",
        "iam.oauth",
        "iam.oauth.secrets.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/surfaces",
        "iam.oauth",
        "iam.oauth.surfaces.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/surfaces",
        "iam.oauth",
        "iam.oauth.surfaces.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/surfaces/{surfaceId}",
        "iam.oauth",
        "iam.oauth.surfaces.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/surfaces/{surfaceId}",
        "iam.oauth",
        "iam.oauth.surfaces.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/flow_configs",
        "iam.oauth",
        "iam.oauth.flowConfigs.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/flow_configs",
        "iam.oauth",
        "iam.oauth.flowConfigs.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/flow_configs/{flowConfigId}",
        "iam.oauth",
        "iam.oauth.flowConfigs.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/scope_profiles",
        "iam.oauth",
        "iam.oauth.scopeProfiles.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/scope_profiles",
        "iam.oauth",
        "iam.oauth.scopeProfiles.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/scope_profiles/{scopeProfileId}",
        "iam.oauth",
        "iam.oauth.scopeProfiles.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/claim_mappings",
        "iam.oauth",
        "iam.oauth.claimMappings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/claim_mappings",
        "iam.oauth",
        "iam.oauth.claimMappings.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/claim_mappings/{mappingId}",
        "iam.oauth",
        "iam.oauth.claimMappings.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/policies",
        "iam.oauth",
        "iam.oauth.policies.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/policies",
        "iam.oauth",
        "iam.oauth.policies.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/policies/{policyId}",
        "iam.oauth",
        "iam.oauth.policies.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/tenant_bindings",
        "iam.oauth",
        "iam.oauth.tenantBindings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/tenant_bindings",
        "iam.oauth",
        "iam.oauth.tenantBindings.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/tenant_bindings/{bindingId}",
        "iam.oauth",
        "iam.oauth.tenantBindings.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/operator_platforms",
        "iam.oauth",
        "iam.oauth.operatorPlatforms.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/operator_platforms",
        "iam.oauth",
        "iam.oauth.operatorPlatforms.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/operator_platforms/{operatorPlatformId}",
        "iam.oauth",
        "iam.oauth.operatorPlatforms.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/operator_platforms/{operatorPlatformId}/pre_authorizations",
        "iam.oauth",
        "iam.oauth.operatorPlatforms.preAuthorizations.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/resource_accounts",
        "iam.oauth",
        "iam.oauth.resourceAccounts.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_accounts",
        "iam.oauth",
        "iam.oauth.resourceAccounts.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}",
        "iam.oauth",
        "iam.oauth.resourceAccounts.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}",
        "iam.oauth",
        "iam.oauth.resourceAccounts.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/custom_menus",
        "iam.oauth",
        "iam.oauth.resourceAccounts.customMenus.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/custom_menus",
        "iam.oauth",
        "iam.oauth.resourceAccounts.customMenus.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/custom_menus/publish",
        "iam.oauth",
        "iam.oauth.resourceAccounts.customMenus.publish",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/verifications",
        "iam.oauth",
        "iam.oauth.resourceAccounts.verifications.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/follow_qr_codes",
        "iam.oauth",
        "iam.oauth.resourceAccounts.followQrCodes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/mini_program_login_checks",
        "iam.oauth",
        "iam.oauth.resourceAccounts.miniProgramLoginChecks.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_accounts/{resourceAccountId}/authorization_refreshes",
        "iam.oauth",
        "iam.oauth.resourceAccounts.authorizationRefreshes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/resource_authorizations",
        "iam.oauth",
        "iam.oauth.resourceAuthorizations.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/resource_authorizations",
        "iam.oauth",
        "iam.oauth.resourceAuthorizations.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/resource_authorizations/{authorizationId}",
        "iam.oauth",
        "iam.oauth.resourceAuthorizations.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/webhook_configs",
        "iam.oauth",
        "iam.oauth.webhookConfigs.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/webhook_configs",
        "iam.oauth",
        "iam.oauth.webhookConfigs.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/webhook_configs/{webhookConfigId}",
        "iam.oauth",
        "iam.oauth.webhookConfigs.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/webhook_configs/{webhookConfigId}",
        "iam.oauth",
        "iam.oauth.webhookConfigs.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/webhook_configs/{webhookConfigId}/verifications",
        "iam.oauth",
        "iam.oauth.webhookConfigs.verifications.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/operational_resources",
        "iam.oauth",
        "iam.oauth.operationalResources.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/operational_resources",
        "iam.oauth",
        "iam.oauth.operationalResources.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/operational_resources/{resourceId}",
        "iam.oauth",
        "iam.oauth.operationalResources.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/operational_resources/{resourceId}",
        "iam.oauth",
        "iam.oauth.operationalResources.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/operational_resources/{resourceId}/publishes",
        "iam.oauth",
        "iam.oauth.operationalResources.publishes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/account_links",
        "iam.oauth",
        "iam.oauth.accountLinks.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/account_links/{accountLinkId}",
        "iam.oauth",
        "iam.oauth.accountLinks.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/grants",
        "iam.oauth",
        "iam.oauth.grants.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/iam/oauth/grants/{grantId}",
        "iam.oauth",
        "iam.oauth.grants.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/callback_events",
        "iam.oauth",
        "iam.oauth.callbackEvents.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/diagnostic_runs",
        "iam.oauth",
        "iam.oauth.diagnosticRuns.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/diagnostic_runs",
        "iam.oauth",
        "iam.oauth.diagnosticRuns.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/diagnostic_runs/{diagnosticRunId}",
        "iam.oauth",
        "iam.oauth.diagnosticRuns.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/iam/oauth/scan_login_settings",
        "iam.oauth",
        "iam.oauth.scanLoginSettings.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/iam/oauth/scan_login_settings",
        "iam.oauth",
        "iam.oauth.scanLoginSettings.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/iam/oauth/scan_login_previews",
        "iam.oauth",
        "iam.oauth.scanLoginPreviews.create",
    ),
];

fn enrich_backend_route(route: HttpRoute) -> HttpRoute {
    if route.required_permission.is_some() {
        return route;
    }
    HttpRoute {
        required_permission: iam_backend_permission_for_operation(route.operation_id),
        ..route
    }
}

static IAM_BACKEND_ENRICHED_ROUTES: std::sync::OnceLock<&'static [HttpRoute]> =
    std::sync::OnceLock::new();

fn enriched_backend_routes() -> &'static [HttpRoute] {
    IAM_BACKEND_ENRICHED_ROUTES.get_or_init(|| {
        let routes: Vec<HttpRoute> = IAM_BACKEND_API_ROUTES
            .iter()
            .copied()
            .map(enrich_backend_route)
            .collect();
        Box::leak(routes.into_boxed_slice())
    })
}

pub fn backend_routes() -> Vec<HttpRoute> {
    IAM_BACKEND_API_ROUTES.to_vec()
}

pub fn iam_backend_enriched_routes() -> &'static [HttpRoute] {
    enriched_backend_routes()
}

pub fn iam_backend_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(enriched_backend_routes())
}

pub fn sdkwork_iam_backend_api_routes() -> Vec<HttpRoute> {
    iam_backend_enriched_routes().to_vec()
}
