use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

const IAM_APP_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions",
        "auth",
        "sessions.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions/login_context_selection",
        "auth",
        "sessions.loginContextSelection.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions/organization_selection",
        "auth",
        "sessions.organizationSelection.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/auth/sessions/current",
        "auth",
        "sessions.current.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/auth/sessions/current",
        "auth",
        "sessions.current.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/auth/sessions/current",
        "auth",
        "sessions.current.delete",
    ),
    HttpRoute::refresh_token(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions/refresh",
        "auth",
        "sessions.refresh",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/password_reset_requests",
        "auth",
        "passwordResetRequests.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/verification_code_requests",
        "auth",
        "verificationCodeRequests.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/password_resets",
        "auth",
        "passwordResets.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/registrations",
        "auth",
        "registrations.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/oauth/providers",
        "oauth",
        "providers.list",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/oauth/scan_login_modes",
        "oauth",
        "scanLoginModes.list",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/authorization_urls",
        "oauth",
        "authorizationUrls.create",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations",
        "oauth",
        "deviceAuthorizations.create",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}",
        "oauth",
        "deviceAuthorizations.retrieve",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/scans",
        "oauth",
        "deviceAuthorizations.scans.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/password_completions",
        "oauth",
        "deviceAuthorizations.passwordCompletions.create",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/session_exchanges",
        "oauth",
        "deviceAuthorizations.sessionExchanges.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/session_completions",
        "oauth",
        "deviceAuthorizations.sessionCompletions.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/oauth/callbacks/{providerCode}",
        "oauth",
        "callbacks.retrieve",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/callbacks/{providerCode}",
        "oauth",
        "callbacks.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/mini_program_sessions",
        "oauth",
        "miniProgramSessions.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/sessions",
        "oauth",
        "sessions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/oauth/account_links",
        "oauth",
        "accountLinks.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/oauth/account_links/{accountLinkId}",
        "oauth",
        "accountLinks.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/oauth/grants",
        "oauth",
        "grants.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/oauth/grants/{grantId}",
        "oauth",
        "grants.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/oauth/authorizations/{authorizationStateId}/completions",
        "oauth",
        "authorizations.completions.create",
    ),
    // Desktop browser-login session bootstrap: the native app redeems a
    // PKCE-bound authorization code (delivered through its deeplink redirect)
    // for a standard dual-token session. Pure anonymous like the QR login
    // device exchanges — the code + PKCE verifier is the proof.
    HttpRoute::public(
        HttpMethod::Post,
        "/app/v3/api/oauth/desktop_sessions",
        "oauth",
        "desktopSessions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/oauth/wechat/payment/start",
        "oauth",
        "wechatPaymentOauth.start",
    ),
    // WeChat redirects the payer's browser back here after authorize with
    // `code` + `state` only — never with platform credentials. The handler
    // restores tenant scope from its own state cookie, so the callback must
    // stay anonymous (no dual-token, no login) or WeChat Pay OAuth breaks.
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/oauth/wechat/payment/callback",
        "oauth",
        "wechatPaymentOauth.callback",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/system/iam/runtime",
        "system",
        "iam.runtime.retrieve",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/system/iam/verification_policy",
        "system",
        "iam.verificationPolicy.retrieve",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/system/iam/account_binding_policy",
        "system",
        "iam.accountBindingPolicy.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/users/current",
        "iam",
        "users.current.retrieve",
    )
    .with_required_permission("iam:self"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/iam/users/current",
        "iam",
        "users.current.update",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/iam/users/current/password",
        "iam",
        "users.current.password.update",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/iam/users/current/email_bindings",
        "iam",
        "users.current.emailBindings.create",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/iam/users/current/email_bindings",
        "iam",
        "users.current.emailBindings.delete",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/iam/users/current/phone_bindings",
        "iam",
        "users.current.phoneBindings.create",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/iam/users/current/phone_bindings",
        "iam",
        "users.current.phoneBindings.delete",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/organizations",
        "iam",
        "organizations.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/organizations/tree",
        "iam",
        "organizations.tree.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/organization_memberships",
        "iam",
        "organizationMemberships.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/departments",
        "iam",
        "departments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/departments/tree",
        "iam",
        "departments.tree.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/department_assignments",
        "iam",
        "departmentAssignments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/positions",
        "iam",
        "positions.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/position_assignments",
        "iam",
        "positionAssignments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/role_bindings",
        "iam",
        "roleBindings.list",
    ),
];

/// IAM operations that intentionally accept no framework credential.
pub const IAM_ANONYMOUS_OPERATION_IDS: &[&str] = &[
    "deviceAuthorizations.create",
    "deviceAuthorizations.retrieve",
    "deviceAuthorizations.sessionExchanges.create",
    "desktopSessions.create",
    "wechatPaymentOauth.callback",
];

/// Session routes resolved by the framework before handler execution.
pub const IAM_FRAMEWORK_SESSION_OPERATION_IDS: &[&str] = &[
    "sessions.current.retrieve",
    "sessions.current.update",
    "sessions.current.delete",
];

/// Credential-entry routes aligned with `SDKWORK_IAM_API_ROUTES` `forbidCredentialHeaders`.
pub const IAM_CREDENTIAL_ENTRY_OPERATION_IDS: &[&str] = &[
    "sessions.create",
    "sessions.loginContextSelection.create",
    "sessions.organizationSelection.create",
    "passwordResetRequests.create",
    "verificationCodeRequests.create",
    "passwordResets.create",
    "registrations.create",
    "authorizationUrls.create",
    "providers.list",
    "deviceAuthorizations.scans.create",
    "deviceAuthorizations.passwordCompletions.create",
    "callbacks.retrieve",
    "callbacks.create",
    "miniProgramSessions.create",
    "sessions.create",
    "iam.runtime.retrieve",
    "iam.verificationPolicy.retrieve",
    "iam.accountBindingPolicy.retrieve",
];

pub fn app_routes() -> Vec<HttpRoute> {
    IAM_APP_API_ROUTES.to_vec()
}

pub fn iam_app_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(IAM_APP_API_ROUTES)
}

pub fn sdkwork_iam_app_api_routes() -> Vec<HttpRoute> {
    app_routes()
}
